---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Physical.media - Album Release Tracker"
keywords:    "Physical.media, PhysicalMedia, Physical media, album releases, album tracker, album release tracker, music, music releases, vinyl releases"
description: "A content-rich album release tracker for discovering new music."
source_link: "https://github.com/JoshM33k/PhysicalMedia"
favicon:     ""
touch_icon:  ""
google_analytics_key: UA-57034301-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
